# Create the Alumni Hall Gym Environment

In [1]:
# including the project directory to the notebook level
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'  # set it to -1 if GPU i snot needed. But set it to the original value after use
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import warnings  

In [2]:
from dataprocess import dataprocessor as dp
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from pandas import DataFrame

with warnings.catch_warnings():  
    warnings.filterwarnings("ignore",category=FutureWarning)
    
    import tensorflow as tf
    config = tf.ConfigProto(log_device_placement=False)
    config.gpu_options.allow_growth = True
    #config = tf.ConfigProto(device_count={'CPU' : 4, 'GPU' : 0}, allow_soft_placement=False, log_device_placement=True)
    session = tf.Session(config=config)
    
    from keras.models import load_model
    from nn_source import models as mp
    from rl_source import alumnienv
    from stable_baselines.common.vec_env import SubprocVecEnv
    from stable_baselines.common import set_global_seeds, make_vec_env

Using TensorFlow backend.


In [3]:
# read the pickled file for ahu data
dfdata = dp.readfile('../data/processed/buildingdata.pkl')

# return pickled df
df = dfdata.return_df(processmethods=['file2df'])

In [4]:
# 0-1 Scale the dataframe before sending it to the environment
scaler = MinMaxScaler(feature_range=(0,1))
dfscaler = scaler.fit(df)

In [5]:
dfscaled = DataFrame(dfscaler.fit_transform(df), index=df.index, columns=df.columns)

In [6]:
# load energy model
energymodel = load_model('../results/lstmtrain/LSTM_model_44_0.01')  # Specify the path where energy is stored







Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [7]:
# important parameters to scale the reward
params = {
    'energy_saved': 1.0,
    'energy_savings_thresh': 0.0,
    'energy_penalty': -1.0,
    'energy_reward_weight': 1.0,
    'comfort': 1.0,
    'comfort_thresh': 0.10,
    'uncomfortable': -1.0,
    'comfort_reward_weight': 1.0,
    'action_minmax': [np.array([df.sat.min()]),
                      np.array([df.sat.max()])]
}

In [8]:
# instantiate the environment
envmodel = alumnienv.Env(
    df=dfscaled,
    obs_space_vars=['oat', 'orh', 'ghi', 'sat', 'avg_stpt'],  # state space variable
    action_space_vars=['sat'],   # action space variable
    action_space_bounds=[[-2.0], [2.0]],  # bounds for real world action space; is scaled internally using the params
    energy_model=energymodel,  # trained lstm model
    model_input_shape=(1, 1, 4),  # lstm model input data shape (no_samples, output_timestep, inputdim)
    model_input_vars=['oat', 'orh', 'ghi','sat'],  # lstm model input variables
    **params
)

/data/nauga/SmartBuildings/venvs/sbvenv1/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


## Test the environment for inidvidual methods

In [9]:
# make sure environment is in train mode
envmodel.trainenv()

In [10]:
# resest environment
envmodel.reset()

array([0.79991203, 0.82282514, 0.58238342, 0.7513201 , 0.45607235])

In [11]:
# Step through the environment eg apply a change of 0.43*F in the up direction
envmodel.step(np.array([0.43]))

(array([0.79991203, 0.82282514, 0.60103627, 0.76295517, 0.45607235]),
 0.0,
 False,
 {})

In [12]:
# make sure environment is in test mode
envmodel.testenv()

In [13]:
# resest environment
envmodel.reset()

array([0.73546375, 0.47605578, 0.        , 0.51102325, 0.57364341])

In [14]:
# Step through the environment eg apply a change of 0.43*F in the down direction
envmodel.step(np.array([-0.43]))

(array([0.73546375, 0.47954249, 0.        , 0.49938818, 0.57364341]),
 0.0,
 False,
 {'time': '2019-09-26 01:50:00',
  'energy': 0.322563499212265,
  'baseline_energy': 0.32253530621528625,
  'reward_energy': -1.0,
  'reward_comfort': 1.0,
  'oat': 0.7354637489469744,
  'orh': 0.47605577951877737,
  'T_rl_disch': 0.49938817625757426,
  'avg_stpt': 0.5736434108527124})

In [15]:
envmodel.seed()

## Creating vectorized version of our environment for Stable Baselines

### see vecenvtest.py inside rl_source. The vectorized environment cannot be created and executed in separate scripts